### ISSUE TITLE
Not broadcasting on mac OS High Sierra

### ISSUE THREAD

**Issue by ferencbrachmann** [dermike/electron-slide-beacon#18]
I just noticed the broadcaster does not work on High Sierra.

**Comment by dermike** [comment]
It will be fixed when https://github.com/sandeepmistry/bleno is updated to support High Sierra.

**Comment by ferencbrachmann** [comment]
https://github.com/sandeepmistry/bleno/issues/341

**Comment by dermike** [comment]
@ferencbrachmann New version published with High Sierra support, please let me know how it runs.
https://github.com/dermike/slide-beacon-app/releases/download/0.4.2/SlideBeacon.zip

**Comment by ferencbrachmann** [comment]
Works like a charm! Thank you!!
